# Define the goal, 0...moveToPose, 1...explore, 2...search, 3...start rotation
int16 action
geometry_msgs/Pose pose
int16 target
---
# Define the result
int16 result_number
---
# Define a feedback message